name: Naukri Profile Updater

on:
  workflow_dispatch:

jobs:
  update_profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb libgbm1 libnss3 libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libasound2

      - name: Install Python packages and Playwright browsers
        run: |
          pip install playwright
          playwright install chromium

      - name: Run automation in headed mode
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: |
          xvfb-run -a -s "-screen 0 1920x1080x24" python update_profile.py
