name: Naukri Profile Updater

on:
  workflow_dispatch:

jobs:
  update_profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb ffmpeg libgbm-dev fonts-liberation

      # No longer need to set up Chrome separately as Playwright manages its own browsers.
      
      - name: Install Python packages and Playwright browsers
        run: |
          pip install playwright
          playwright install chromium

      - name: Run automation with recording
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          # Although our script forces headed mode (headless=False), we set HEADLESS as false here for clarity.
          HEADLESS: "false"
        run: |
          # Start virtual display
          Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset &
          export DISPLAY=:99
          
          # Start recording the display
          ffmpeg -y -f x11grab -video_size 1920x1080 -framerate 15 -i :99 -codec:v libx264 -preset ultrafast output.mp4 2> ffmpeg.log &
          FFMPEG_PID=$!
          
          # Run the main Playwright automation script (update_profile.py)
          python update_profile.py || SCREENSHOT_NEEDED=1
          
          # Stop recording and wait for the process to end
          kill $FFMPEG_PID
          wait $FFMPEG_PID
          sleep 5

      - name: Upload artifacts on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: error-artifacts
          path: |
            screenshots/*.png
            ffmpeg.log

      - name: Upload screen recording
        uses: actions/upload-artifact@v4
        with:
          name: browser-recording
          path: output.mp4
